
valores_ = {'ACCESORIOS': 'AC', 'AUTOMOTRIZ': 'AU',
 'BELLEZA': 'BE', 'COMERCIO INDUSTRIAL': 'CI', 
 'COMIDA': 'CO', 'CUIDADO PERSONAL': 'CP',
 'CALZADO': 'CZ', 'DEPORTE': 'DP', 'FESTEJO': 'FE ',
 'FERRETERÍA': 'FR', 'HOGAR': 'HG', 'INSUMOS': 'IN',
 'JUGUETES': 'JG', 'OFICINA': 'OF', 
 'PERFUME': 'PE', 'PIPAS Y BOQUILLAS': 'PI',
 'PRODUCTOS DE LIMPIEZA': 'PL', 'ROPA': 'RP', 
 'TECNOLOGIA': 'TG'}

